apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-volume
  labels:
    app: redis

spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: "/home/student/gitlab/redis/"
