apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio-volume
  labels:
    app: minio

spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/home/student/gitlab/minio/"
