apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql-volume
  labels:
    app: postgresql

spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: "/home/student/gitlab/postgresql/"
