apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly-volume
  labels:
    app: gitaly

spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: "/home/student/gitlab/gitaly/"
